ssh k8s-1 "apt-get update && apt-get install python -y"
ssh k8s-2 "apt-get update && apt-get install python -y"
ssh k8s-3 "apt-get update && apt-get install python -y"
ssh k8s-slave-1 "apt-get update && apt-get install python -y"
ssh k8s-slave-2 "apt-get update && apt-get install python -y"
ssh k8s-slave-3 "apt-get update && apt-get install python -y"
